bigswitch/horizon-bsn

rhel/python-horizon-bsn.spec, setup.cfg
=> tag for mitaka release

rhel/python-horizon-bsn.spec, setup.cfg
=> fix changelog history

horizon_bsn/content/connections/routerrules/forms.py, horizon_bsn/content/connections/routerrules/rulemanager.py, horizon_bsn/content/connections/routerrules/tabs.py, horizon_bsn/content/connections/templates/connections/routerrules/grid.html, rhel/python-horizon-bsn.spec, setup.cfg
- make diagonal entries hyphenated
- show nexthops in conflicted policies modal
- display not one, but all conflicting policies in the conflict modal
- allow any-any to be clickable
=> BVS-6565 router policy look and feel enhancements

horizon_bsn/content/connections/routerrules/rulemanager.py, rhel/python-horizon-bsn.spec, setup.cfg
- last rule cannot be deleted no longer applies
=> OSP-19 ensure policy is deleted in MLR case

horizon_bsn/content/connections/routerrules/rulemanager.py, rhel/python-horizon-bsn.spec, setup.cfg
=> OSP-19 ensure policy is deleted in MLR case [cherry-pick]

horizon_bsn/content/connections/routerrules/tabs.py, rhel/python-horizon-bsn.spec, setup.cfg
=> OSP-26: check for presence of routers

horizon_bsn/content/connections/routerrules/tabs.py, rhel/python-horizon-bsn.spec, setup.cfg
Conflicts:
rhel/python-horizon-bsn.spec
setup.cfg
=> OSP-26: check for presence of routers [cherry-pick]

.idea/encodings.xml, .idea/horizon-bsn.iml, .idea/misc.xml, .idea/modules.xml, .idea/workspace.xml, horizon_bsn/content/connections/routerrules/rulemanager.py, horizon_bsn/content/connections/routerrules/tabs.py, rhel/python-horizon-bsn.spec, setup.cfg
=> OSP-19: OSP-26: [cherry-pick]

horizon_bsn/content/connections/reachability_tests/forms.py, rhel/python-horizon-bsn.spec, setup.cfg
=> OSP-36: member user should be able to create reachability test

horizon_bsn/content/connections/reachability_tests/forms.py, rhel/python-horizon-bsn.spec, setup.cfg
=> OSP-36: member user should be able to create reachability test [cherry-pick]

horizon_bsn/content/connections/reachability_tests/forms.py, rhel/python-horizon-bsn.spec, setup.cfg
=> OSP-36: missed a replacement for quicktest tenant get

horizon_bsn/content/connections/reachability_tests/forms.py, rhel/python-horizon-bsn.spec, setup.cfg
=> OSP-36: missed a replacement for quicktest tenant get [cherry-pick]

horizon_bsn/api/neutron.py, horizon_bsn/content/connections/templates/connections/reachability_tests/_detail_overview.html, horizon_bsn/content/connections/templates/connections/reachability_tests/detail.html, rhel/python-horizon-bsn.spec, setup.cfg
Reviewer: @sarath-kumar 
this is in continuation of neutron plugin review: https://review.openstack.org/#/c/512768
=> BCF-6592: add logical path to the output testpath on horizon

horizon_bsn/api/neutron.py, horizon_bsn/content/connections/templates/connections/reachability_tests/_detail_overview.html, horizon_bsn/content/connections/templates/connections/reachability_tests/detail.html, rhel/python-horizon-bsn.spec, setup.cfg
Reviewer: trivial
cherry-pick change.
=> BCF-6592: add logical path to the output testpath on horizon [cherry-pick]

build/build-rhel-packages.sh, build/openstack_horizon_bsn.build, build/openstack_horizon_bsn_pull_req.build, build/precheckin.sh, build/upload_to_pypi.sh, rhel/python-horizon-bsn.spec, setup.cfg
=> IN-250: ensure build jobs don't pip/apt-get install [cherry-pick]

rhel/python-horizon-bsn.spec, setup.cfg
- creating the ocata branch with a baseline version
=> update version for ocata

rhel/python-horizon-bsn.spec, setup.cfg
=> bump to stable version of controller

rhel/python-horizon-bsn.spec
=> oops, date order incorrect in copy-paste

rhel/python-horizon-bsn.spec
=> messed up year in spec file changelog

horizon_bsn/content/connections/network_template/tables.py, horizon_bsn/content/connections/reachability_tests/tables.py, rhel/python-horizon-bsn.spec, setup.cfg
=> BCF-9905: fix superclass deprecations causing error during horizon startup [cherry-pick]

build/build-rhel-packages.sh, rhel/horizon_container_workaround.sh
Reviewer: @sarath-kumar 
- cherry-pick
=> EXT-80: customize horizon container for bsn plugin enablement [cherry-pick]

horizon_bsn/bsn_neutronclient/v2_0/bsn_plugin_client.py, setup.cfg
Reviewer: trivial
- test changes - will be reverted if rpm build fails
=> BCF-9952: include CLI extension in horizon package as well

build/precheckin.sh, build/upload_to_pypi.sh
Reviewer: trivial
- we updated to ubuntu 16.04 for build container
- updates the build script
=> build container changes

build/precheckin.sh
=> minor fix to precheckin validation check

build/upload_to_pypi.sh, rhel/python-horizon-bsn.spec, setup.cfg
=> increase delay

test-requirements.txt
=> reqs: update dependent libraries with license info

rhel/Dockerfile
Reviewer: trivial
- cherry-pick
=> add Dockerfile for RHOSP container build [cherry-pick]

rhel/Dockerfile
does this work? need to do a quick push and test.
if it doesn't, would revert it.
=> test license addition

rhel/Dockerfile
This reverts commit 186abc17adb68c2dfc8779e202b38872a80f1d4a.
=> Revert "test license addition"

LICENSE
=> add missing info to APL

rhel/Dockerfile
=> add license info to RHOSP container

rhel/Dockerfile
=> add license info to RHOSP container + change version to 13.0 [cherry-pick]
